name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  backend-lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Загрузка кода репозитория
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --force-reinstall -r requirements.txt # dont use cache, can not resolve version conflict

    - name: Линтинг с flake8
      run: flake8 .

    - name: Проверка форматирования через black
      run: black --check .

    - name: Проверка порядка импортов через isort
      run: isort --check-only .

    - name: Запуск тестов с pytest
      # run: pytest tests/ -v --cov=app --cov-report=term
      run: python -m pytest tests/ -v --cov=app --cov-report=term --cache-clear
      env:
        PYTHONPATH: .

  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка кода репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Установка зависимостей фронтенда
        run: npm ci
        working-directory: ./client

      - name: Проверка HTML
        run: npx html-validate "*.html"
        working-directory: ./client

      - name: Проверка CSS
        run: npx stylelint "*.css"
        working-directory: ./client

      - name: Проверка JavaScript
        run: npx eslint "*.js"
        working-directory: ./client